### ISSUE TITLE
Switching between related functions

### ISSUE THREAD

**Issue by cgd8d** [CMA-ES/c-cmaes#16]
In my application, I first optimize a function f(x1, ..., xn) which is relatively cheap; then I add a perturbation to that function which is very expensive to compute, so I would like to retain as much information from the first optimization as possible.  It is clear how to use the optimum (x1, ..., xn) from the first optimization as a starting point for the second, but I am unsure how best to retain covariance matrix and step size information.  There are two related scenarios:

1) The perturbation takes the form g(x1, ..., xn), so the dimension is the same.  In this case, is this the right approach?

    /* Evaluations use f(x1, ..., xn) up to here. */
    cmaes_WriteToFile(evo_ptr, "resume", filename);
    cmaes_exit(evo_ptr);
    cmaes_init(evo_ptr, dimension, initialX, initialStdDev, seed, lambda, input_parameter_filename);
    cmaes_resume_distribution(evo_ptr, filename);
    /* Evaluations continue with f(x1, ..., xn) + g(x1, ..., xn). */

2) The dimension of the problem also increases, so the function becomes f(x1, ..., xn) + g(x1, ..., xn, ..., xm).  Is there a recommended way to retain information about the n dimensions which have already been studied, while feeding in default values for new dimensions?

Thanks!

**Comment by nikohansen** [comment]
1) looks fine to me. It would be interesting to see the behavior before and after the restart (from the default plots). 

2) I am not aware of systematic experimental results on this situation. Naturally, what will be best depends very much on the amount of effect the new variables have on the optimal setting of the already optimized variables. Generally, setting all covariances where new variables are involved to zero seems reasonable, while it's more difficult to decide on the "right" initial variances.

**Comment by cgd8d** [comment]
Thank you for your feedback!  This gets me going; if anything interesting results, I'll be sure to add it to this thread.

**Comment by nikohansen** [comment]
excellent, I am curious, as using covariance information from previous runs successfully is in my experience more difficult than one would expect. Let me add that careful (re-)consideration of the new initial `sigma` is in order, as it might strongly depend on the termination condition of the previous run.
