### ISSUE TITLE
Eigen decomposition and Gaussian noise vector question

### ISSUE THREAD

**Issue by avaneev** [CMA-ES/c-cmaes#20]
This is not so much an issue, but a fellow researcher question. In CMA-ES an Eigen decomposition is used. While it provides a good estimation of space directionality of sample distribution, this method only ranks the standard deviations in the sample distribution. Yet, CMA-ES uses `t->rgD[i]` that are ranked. So, when a Gaussian noise vector is generated, its components do not correspond to standard deviations of the sample distribution along its axes. Maybe this is already handled, but I have not found how.

Also I've spotted that in ` cmaes_interface.cpp:1939` the `t->rgD[i] = sqrt(t->rgD[i]);` equation is used. From my personal experience, the problem is, Householder and QLalgo may produce small negative values in `t->rgD`, so a `sqrt(abs(t->rgD[i]))` is needed to handle such cases.

**Comment by avaneev** [comment]
Well, this may not be applicable to CMA-ES, but optimization via Gaussian vector sampling works equally well if you just use standard deviations across main diagonal of covariance matrix, without applying eigenvector rotation, so there is not need in eigendecomposition and full-rank covariance matrix update. This is also implied by the fact CMA-ES method is working while it uses ranked standard deviations.

**Comment by avaneev** [comment]
A bit of background information: I'm now working on a method that uses Gaussian vector sampling and population fitness sorting and weighting similar to CMA-ES, just without CMA. I've initially implemented eigendecomposition and eigenvector rotation, but later tests revealed that these operations are not needed. I have a set of 57 14-dimensional functions that are randomly rotated and offseted similar to BBOB suite. My method solves 61% of them while CMA-ES solves 69%, in roughly similar time, but I'm still at the very early steps of development (only two days into it). What I have found, is that population weighting is the most important aspect - it is this aspect that moves sample distribution into optimum. Another important element is standard deviation adaptation - which you do in CMA-ES.

**Comment by avaneev** [comment]
Basically, method even works (at a bit reduced efficiency) if you draw standard deviation values randomly from the std.dev vector, or use a summary RMS value of all standard deviations, meaning it mostly needs a radial standard deviation estimate.

**Comment by nikohansen** [comment]
> Well, this may not be applicable to CMA-ES, but optimization via Gaussian vector sampling works equally well if you just use standard deviations across main diagonal of covariance matrix

I am sure it works equally well on some functions, but I am also sure it doesn't work even remotely equally well on others (unless I misunderstand what you are saying). It all depends on what kind of functions we want to be able to solve. The following cigar function cannot be solved (that is: reaching a f-value of 1e-8 starting from all-ones in dimension 10) with a diagonal covariance matrix in any reasonable time:

![image](https://user-images.githubusercontent.com/7316439/46813551-36dc2700-cd77-11e8-9f79-ee6516bb98dd.png)

Check it out!

**Comment by avaneev** [comment]
Yes, that's a complex function from what I can tell. However, my point is that why your method works while it uses incorrect (sorted) sigma values after Eigen decomposition. My idea is that probably Eigen decomposition is not necessary at all, but covariance update procedure may need to be changed a bit.

**Comment by nikohansen** [comment]
> However, my point is that why your method works while it uses incorrect (sorted) sigma values after Eigen decomposition.

That sounds pretty unlikely. One can use any permutation of eigenvalues and eigenvectors, as long as the same permutation is used for both, without changing anything at all. I usually like to sort them, because it makes accessing the smallest and largest eigenvalue simpler.

**Comment by avaneev** [comment]
Exactly the sorting is what I think is incorrect, because the eigenvectors you then use do not correspond to eigenvalues. Eigenvectors define "gaussian space rotation" and eigenvalues define sizes of gaussian distributions. When you sort eigenvalues the sizes are assigned purely on random and do not correspond to rotation matrix. Yet your method is working. That was idea of my message here - maybe your method may work in a much more computationally-inexpensive manner.

**Comment by nikohansen** [comment]
I cannot speak for the `cpp` code, but in the `C` code the eigenvalues and -vectors are sorted [here](https://github.com/CMA-ES/c-cmaes/blob/eda8268ee4c8c9fbe4d2489555ae08f8a8c949b5/src/cmaes.c#L2103). The code isn't likely to pass quite basic tests if eigenvectors and eigenvalues were sorted differently.

**Comment by avaneev** [comment]
I assumed that such eigenpair sort is probably not a correct operation. Eigenvectors and eigenvalues form a system, rotation matrix, I do not think exchanging elements won't break the orientation.

But I may be wrong, of course. In that case this "issue" is inadequate. Sorry for taking your time.

**Comment by nikohansen** [comment]
The permutation does really no more than changing `d1 v1 + d2 v2` into `d2 v2 + d1 v1`. That's how these eigenvalues and vectors are in effect used. If we do not use the same permutation we may end up with `d1 v2 + d2 v1` which is indeed different.
